/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class KTP extends javax.swing.JFrame {

    /**
     * Creates new form KTP
     */
    public KTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_ttl = new javax.swing.JLabel();
        lbl_jk = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        lbl_rtrw = new javax.swing.JLabel();
        lbl_keldes = new javax.swing.JLabel();
        lbl_kecamatan = new javax.swing.JLabel();
        lbl_kota = new javax.swing.JLabel();
        lbl_agama = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_goldar = new javax.swing.JLabel();
        lbl_pekerjaan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TF_nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TF_ttl1 = new javax.swing.JTextField();
        TF_ttl2 = new javax.swing.JTextField();
        RB_laki = new javax.swing.JRadioButton();
        RB_perempuan = new javax.swing.JRadioButton();
        TF_alamat = new javax.swing.JTextField();
        TF_rt = new javax.swing.JTextField();
        TF_rw = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_keldesa = new javax.swing.JTextField();
        TF_kecamatan = new javax.swing.JTextField();
        TF_kota = new javax.swing.JTextField();
        CB_agama = new javax.swing.JComboBox();
        CB_status = new javax.swing.JComboBox();
        CB_goldar = new javax.swing.JComboBox();
        TF_pekerjaan = new javax.swing.JTextField();
        RB_wni = new javax.swing.JRadioButton();
        RB_wna = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btn_daftar = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lbl_judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_judul.setText("FORM KARTU TANDA PENDUDUK");

        lbl_nama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_nama.setText("Nama");

        lbl_ttl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_ttl.setText("Tempat/Tanggal Lahir");

        lbl_jk.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_jk.setText("Jenis Kelamin");

        lbl_alamat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_alamat.setText("Alamat");

        lbl_rtrw.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_rtrw.setText("RT/RW");

        lbl_keldes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_keldes.setText("Kel/Desa");

        lbl_kecamatan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_kecamatan.setText("Kecamatan");

        lbl_kota.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_kota.setText("Kota");

        lbl_agama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_agama.setText("Agama");

        lbl_status.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_status.setText("Status");

        lbl_goldar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_goldar.setText("Golongan Darah");

        lbl_pekerjaan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_pekerjaan.setText("Pekerjaan");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Kewarganegaraan");

        TF_nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("/");

        TF_ttl1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_ttl2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        buttonGroup1.add(RB_laki);
        RB_laki.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RB_laki.setText("Laki-laki");

        buttonGroup1.add(RB_perempuan);
        RB_perempuan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RB_perempuan.setText("Perempuan");

        TF_alamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_rt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_rw.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("/");

        TF_keldesa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_kecamatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_kota.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        CB_agama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CB_agama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Katholik", "Kristen", "Hindu", "Buddha", "Islam" }));

        CB_status.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CB_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KAWIN", "BELUM KAWIN" }));

        CB_goldar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CB_goldar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A", "A-", "AB+", "AB", "AB-", "B+", "B", "B-", "O+", "O", "O-" }));

        TF_pekerjaan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        buttonGroup2.add(RB_wni);
        RB_wni.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RB_wni.setText("WNI");

        buttonGroup2.add(RB_wna);
        RB_wna.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RB_wna.setText("WNA");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("FORM ISI");

        btn_daftar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_daftar.setText("DAFTAR");
        btn_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftarActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_daftar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_rtrw)
                                        .addComponent(lbl_keldes)
                                        .addComponent(lbl_kecamatan)
                                        .addComponent(lbl_kota))
                                    .addComponent(lbl_ttl))
                                .addComponent(lbl_nama)
                                .addComponent(lbl_jk)
                                .addComponent(lbl_alamat)
                                .addComponent(lbl_agama)
                                .addComponent(lbl_status)
                                .addComponent(lbl_goldar)
                                .addComponent(lbl_pekerjaan)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(TF_ttl1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1))
                                        .addComponent(RB_laki))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RB_perempuan)
                                        .addComponent(TF_ttl2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(TF_alamat)
                                .addComponent(TF_nama)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TF_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TF_rw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TF_keldesa)
                                .addComponent(TF_kecamatan)
                                .addComponent(TF_kota)
                                .addComponent(CB_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CB_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CB_goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TF_pekerjaan)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(RB_wni)
                                    .addGap(18, 18, 18)
                                    .addComponent(RB_wna))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel3))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(lbl_judul))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_judul)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama)
                    .addComponent(TF_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ttl)
                    .addComponent(jLabel1)
                    .addComponent(TF_ttl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_ttl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jk)
                    .addComponent(RB_laki)
                    .addComponent(RB_perempuan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_alamat)
                    .addComponent(TF_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rtrw)
                    .addComponent(TF_rt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_rw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_keldes)
                    .addComponent(TF_keldesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kecamatan)
                    .addComponent(TF_kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kota)
                    .addComponent(TF_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agama)
                    .addComponent(CB_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_status)
                    .addComponent(CB_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_goldar)
                    .addComponent(CB_goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pekerjaan)
                    .addComponent(TF_pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(RB_wni)
                    .addComponent(RB_wna))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_daftar)
                    .addComponent(btn_reset))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftarActionPerformed
        // TODO add your handling code here:
        outputKTP output = new outputKTP();
        output.TF_nama3.setText(this.TF_nama.getText());
        output.TF_ttl3.setText(this.TF_ttl1.getText());
        output.TF_ttl4.setText(this.TF_ttl2.getText());
        output.TF_alamat3.setText(this.TF_alamat.getText());
        output.TF_rt2.setText(this.TF_rt.getText());
        output.TF_rw3.setText(this.TF_rw.getText());
        output.TF_keldesa2.setText(this.TF_keldesa.getText());
        output.TF_kecamatan2.setText(this.TF_kecamatan.getText());
        output.TF_kota2.setText(this.TF_kota.getText());
        output.TF_agama2.setText(this.CB_agama.getSelectedItem().toString());
        output.TF_status2.setText(this.CB_status.getSelectedItem().toString());
        output.TF_goldar2.setText(this.CB_goldar.getSelectedItem().toString());
        
        String JenisKelamin = null ;
        if(RB_laki.isSelected())
            output.TF_jk2.setText(this.RB_laki.getText());
        else if(RB_perempuan.isSelected())
            output.TF_jk2.setText(this.RB_perempuan.getText());
        
        String waganegara = null ;
        if(RB_wna.isSelected())
            output.TF_kwn2.setText(this.RB_wna.getText());
        else if(RB_wni.isSelected())
            output.TF_kwn2.setText(this.RB_wni.getText());
        
       
                output.setVisible(true);
    }//GEN-LAST:event_btn_daftarActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        TF_nama.setText("");
        TF_ttl1.setText("");
        TF_ttl2.setText("");
        TF_alamat.setText("");
        TF_rt.setText("");
        TF_rw.setText("");
        TF_keldesa.setText("");
        TF_kecamatan.setText("");
        TF_kota.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        TF_pekerjaan.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB_agama;
    private javax.swing.JComboBox CB_goldar;
    private javax.swing.JComboBox CB_status;
    private javax.swing.JRadioButton RB_laki;
    private javax.swing.JRadioButton RB_perempuan;
    private javax.swing.JRadioButton RB_wna;
    private javax.swing.JRadioButton RB_wni;
    private javax.swing.JTextField TF_alamat;
    private javax.swing.JTextField TF_kecamatan;
    private javax.swing.JTextField TF_keldesa;
    private javax.swing.JTextField TF_kota;
    private javax.swing.JTextField TF_nama;
    private javax.swing.JTextField TF_pekerjaan;
    private javax.swing.JTextField TF_rt;
    private javax.swing.JTextField TF_rw;
    private javax.swing.JTextField TF_ttl1;
    private javax.swing.JTextField TF_ttl2;
    private javax.swing.JButton btn_daftar;
    private javax.swing.JButton btn_reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_agama;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_goldar;
    private javax.swing.JLabel lbl_jk;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_kecamatan;
    private javax.swing.JLabel lbl_keldes;
    private javax.swing.JLabel lbl_kota;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_pekerjaan;
    private javax.swing.JLabel lbl_rtrw;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_ttl;
    // End of variables declaration//GEN-END:variables
}
