/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class outputKTP extends javax.swing.JFrame {

    /**
     * Creates new form outputKTP
     */
    public outputKTP() {
        initComponents();
    }

    outputKTP(String lbl_nama, String lbl_ttl1, String lbl_ttl2, String lbl_alamat, String lbl_rt, String lbl_rw, String lbl_keldesa, String lbl_kecamatan, String lbl_kota, String lbl_pekerjaan, String lbl_agama, String lbl_status, String lbl_goldar) {
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_judul2 = new javax.swing.JLabel();
        lbl_nama2 = new javax.swing.JLabel();
        lbl_ttl2 = new javax.swing.JLabel();
        lbl_jk2 = new javax.swing.JLabel();
        lbl_alamat2 = new javax.swing.JLabel();
        lbl_rtrw2 = new javax.swing.JLabel();
        lbl_keldes = new javax.swing.JLabel();
        lbl_kecamatan = new javax.swing.JLabel();
        lbl_kota = new javax.swing.JLabel();
        lbl_agama = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_goldar = new javax.swing.JLabel();
        lbl_pekerjaan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TF_nama3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TF_ttl3 = new javax.swing.JTextField();
        TF_ttl4 = new javax.swing.JTextField();
        TF_alamat3 = new javax.swing.JTextField();
        TF_rt2 = new javax.swing.JTextField();
        TF_rw3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_keldesa2 = new javax.swing.JTextField();
        TF_kecamatan2 = new javax.swing.JTextField();
        TF_kota2 = new javax.swing.JTextField();
        TF_pekerjaan2 = new javax.swing.JTextField();
        lbl_isi = new javax.swing.JLabel();
        TF_jk2 = new javax.swing.JTextField();
        TF_agama2 = new javax.swing.JTextField();
        TF_status2 = new javax.swing.JTextField();
        TF_goldar2 = new javax.swing.JTextField();
        TF_kwn2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        lbl_judul2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_judul2.setText("FORM KARTU TANDA PENDUDUK");

        lbl_nama2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_nama2.setText("Nama");

        lbl_ttl2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_ttl2.setText("Tempat/Tanggal Lahir");

        lbl_jk2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_jk2.setText("Jenis Kelamin");

        lbl_alamat2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_alamat2.setText("Alamat");

        lbl_rtrw2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_rtrw2.setText("RT/RW");

        lbl_keldes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_keldes.setText("Kel/Desa");

        lbl_kecamatan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_kecamatan.setText("Kecamatan");

        lbl_kota.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_kota.setText("Kota");

        lbl_agama.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_agama.setText("Agama");

        lbl_status.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_status.setText("Status");

        lbl_goldar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_goldar.setText("Golongan Darah");

        lbl_pekerjaan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_pekerjaan.setText("Pekerjaan");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Kewarganegaraan");

        TF_nama3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("/");

        TF_ttl3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_ttl4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_alamat3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_rt2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_rw3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("/");

        TF_keldesa2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_kecamatan2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_kota2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_pekerjaan2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbl_isi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_isi.setText("FORM ISI");

        TF_jk2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_agama2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_status2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_goldar2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        TF_kwn2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_rtrw2)
                                    .addComponent(lbl_keldes)
                                    .addComponent(lbl_kecamatan)
                                    .addComponent(lbl_kota))
                                .addComponent(lbl_ttl2))
                            .addComponent(lbl_nama2)
                            .addComponent(lbl_jk2)
                            .addComponent(lbl_alamat2)
                            .addComponent(lbl_agama)
                            .addComponent(lbl_status)
                            .addComponent(lbl_goldar)
                            .addComponent(lbl_pekerjaan)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TF_ttl3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_ttl4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TF_alamat3)
                            .addComponent(TF_nama3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TF_rt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_rw3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TF_keldesa2)
                            .addComponent(TF_kecamatan2)
                            .addComponent(TF_kota2)
                            .addComponent(TF_pekerjaan2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lbl_isi))
                            .addComponent(TF_jk2)
                            .addComponent(TF_agama2)
                            .addComponent(TF_status2)
                            .addComponent(TF_goldar2)
                            .addComponent(TF_kwn2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbl_judul2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_judul2)
                .addGap(18, 18, 18)
                .addComponent(lbl_isi)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama2)
                    .addComponent(TF_nama3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ttl2)
                    .addComponent(jLabel1)
                    .addComponent(TF_ttl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_ttl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jk2)
                    .addComponent(TF_jk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_alamat2)
                    .addComponent(TF_alamat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rtrw2)
                    .addComponent(TF_rt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_rw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_keldes)
                    .addComponent(TF_keldesa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kecamatan)
                    .addComponent(TF_kecamatan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kota)
                    .addComponent(TF_kota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agama)
                    .addComponent(TF_agama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_status)
                    .addComponent(TF_status2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_goldar)
                    .addComponent(TF_goldar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pekerjaan)
                    .addComponent(TF_pekerjaan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TF_kwn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outputKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outputKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outputKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outputKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outputKTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField TF_agama2;
    public static javax.swing.JTextField TF_alamat3;
    public static javax.swing.JTextField TF_goldar2;
    public static javax.swing.JTextField TF_jk2;
    public static javax.swing.JTextField TF_kecamatan2;
    public static javax.swing.JTextField TF_keldesa2;
    public static javax.swing.JTextField TF_kota2;
    public static javax.swing.JTextField TF_kwn2;
    public static javax.swing.JTextField TF_nama3;
    public static javax.swing.JTextField TF_pekerjaan2;
    public static javax.swing.JTextField TF_rt2;
    public static javax.swing.JTextField TF_rw3;
    public static javax.swing.JTextField TF_status2;
    public static javax.swing.JTextField TF_ttl3;
    public static javax.swing.JTextField TF_ttl4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_agama;
    private javax.swing.JLabel lbl_alamat2;
    private javax.swing.JLabel lbl_goldar;
    private javax.swing.JLabel lbl_isi;
    private javax.swing.JLabel lbl_jk2;
    private javax.swing.JLabel lbl_judul2;
    private javax.swing.JLabel lbl_kecamatan;
    private javax.swing.JLabel lbl_keldes;
    private javax.swing.JLabel lbl_kota;
    private javax.swing.JLabel lbl_nama2;
    private javax.swing.JLabel lbl_pekerjaan;
    private javax.swing.JLabel lbl_rtrw2;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_ttl2;
    // End of variables declaration//GEN-END:variables
}
